package com.germanfica.accessingdatamysql;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

@Controller // This means that this class is a Controller
@RequestMapping(path = "/demo") // This means URL's start with /demo (after Application path)
public class MainController {
    // == fields ==
    private UserRepository userRepository;

    // == constructors ==
    @Autowired // This means to get the bean called userRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MainController(UserRepository userRepository) {
        this.userRepository = userRepository;
    }

    // == request methods ==
    @PostMapping(path="/add") // Map ONLY POST Requests
    public @ResponseBody String addUser (@RequestParam String name, @RequestParam String email){
        User n = new User();
        n.setName(name);
        n.setEmail(email);

        Book b = new Book();
        b.setName("Clean Code");
        b.setAuthor("Robert Cecil Martin");

        n.getBooks().add(b); // Add book reference to a user
        b.getUsers().add(n); // Add user reference to a book

        userRepository.save(n); // Save the user in the database

        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<User> getAllUsers() {
        // This returns a JSON or XML with the users
        return userRepository.findAll();
    }
}
